### ISSUE TITLE
Issue : cannot access local variable 'project_executions_total' where it is not associated with a value

### ISSUE THREAD

**Issue by Zwordi** [phsmith/rundeck_exporter#89]
Hello,

Running 2.6.5 we’re getting this traceback toward rundeck 4.11:
```
1.1" 200 None
rundeck-rundeck_exporter-1  | Traceback (most recent call last):
rundeck-rundeck_exporter-1  |   File "/usr/local/lib/python3.12/wsgiref/handlers.py", line 137, in run
rundeck-rundeck_exporter-1  |     self.result = application(self.environ, self.start_response)
rundeck-rundeck_exporter-1  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rundeck-rundeck_exporter-1  |   File "/usr/local/lib/python3.12/site-packages/prometheus_client/exposition.py", line 128, in prometheus_app
rundeck-rundeck_exporter-1  |     status, headers, output = _bake_output(registry, accept_header, accept_encoding_header, params, disable_compression)
rundeck-rundeck_exporter-1  |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rundeck-rundeck_exporter-1  |   File "/usr/local/lib/python3.12/site-packages/prometheus_client/exposition.py", line 104, in _bake_output
rundeck-rundeck_exporter-1  |     output = encoder(registry)
rundeck-rundeck_exporter-1  |              ^^^^^^^^^^^^^^^^^
rundeck-rundeck_exporter-1  |   File "/usr/local/lib/python3.12/site-packages/prometheus_client/openmetrics/exposition.py", line 21, in generate_latest
rundeck-rundeck_exporter-1  |     for metric in registry.collect():
rundeck-rundeck_exporter-1  |   File "/usr/local/lib/python3.12/site-packages/prometheus_client/registry.py", line 97, in collect
rundeck-rundeck_exporter-1  |     yield from collector.collect()
rundeck-rundeck_exporter-1  |   File "/app/rundeck_exporter.py", line 508, in collect
rundeck-rundeck_exporter-1  |     for project_execution_record_group, project_executions_total in project_execution_records:
rundeck-rundeck_exporter-1  |   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 619, in result_iterator
rundeck-rundeck_exporter-1  |     yield _result_or_cancel(fs.pop())
rundeck-rundeck_exporter-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
rundeck-rundeck_exporter-1  |   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 317, in _result_or_cancel
rundeck-rundeck_exporter-1  |     return fut.result(timeout)
rundeck-rundeck_exporter-1  |            ^^^^^^^^^^^^^^^^^^^
rundeck-rundeck_exporter-1  |   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 456, in result
rundeck-rundeck_exporter-1  |     return self.__get_result()
rundeck-rundeck_exporter-1  |            ^^^^^^^^^^^^^^^^^^^
rundeck-rundeck_exporter-1  |   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
rundeck-rundeck_exporter-1  |     raise self._exception
rundeck-rundeck_exporter-1  |   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
rundeck-rundeck_exporter-1  |     result = self.fn(*self.args, **self.kwargs)
rundeck-rundeck_exporter-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rundeck-rundeck_exporter-1  |   File "/app/rundeck_exporter.py", line 309, in get_project_executions
rundeck-rundeck_exporter-1  |     return project_execution_records, project_executions_total
rundeck-rundeck_exporter-1  |                                       ^^^^^^^^^^^^^^^^^^^^^^^^
rundeck-rundeck_exporter-1  | UnboundLocalError: cannot access local variable 'project_executions_total' where it is not associated with a value
rundeck-rundeck_exporter-1  | Traceback (most recent call last):
rundeck-rundeck_exporter-1  |   File "/usr/local/lib/python3.12/wsgiref/handlers.py", line 137, in run
rundeck-rundeck_exporter-1  |     self.result = application(self.environ, self.start_response)
rundeck-rundeck_exporter-1  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rundeck-rundeck_exporter-1  |   File "/usr/local/lib/python3.12/site-packages/prometheus_client/exposition.py", line 128, in prometheus_app
rundeck-rundeck_exporter-1  |     status, headers, output = _bake_output(registry, accept_header, accept_encoding_header, params, disable_compression)
rundeck-rundeck_exporter-1  |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rundeck-rundeck_exporter-1  |   File "/usr/local/lib/python3.12/site-packages/prometheus_client/exposition.py", line 104, in _bake_output
rundeck-rundeck_exporter-1  |     output = encoder(registry)
rundeck-rundeck_exporter-1  |              ^^^^^^^^^^^^^^^^^
rundeck-rundeck_exporter-1  |   File "/usr/local/lib/python3.12/site-packages/prometheus_client/openmetrics/exposition.py", line 21, in generate_latest
rundeck-rundeck_exporter-1  |     for metric in registry.collect():
rundeck-rundeck_exporter-1  |   File "/usr/local/lib/python3.12/site-packages/prometheus_client/registry.py", line 97, in collect
rundeck-rundeck_exporter-1  |     yield from collector.collect()
rundeck-rundeck_exporter-1  |   File "/app/rundeck_exporter.py", line 508, in collect
rundeck-rundeck_exporter-1  |     for project_execution_record_group, project_executions_total in project_execution_records:
rundeck-rundeck_exporter-1  |   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 619, in result_iterator
rundeck-rundeck_exporter-1  |     yield _result_or_cancel(fs.pop())
rundeck-rundeck_exporter-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
rundeck-rundeck_exporter-1  |   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 317, in _result_or_cancel
rundeck-rundeck_exporter-1  |     return fut.result(timeout)
rundeck-rundeck_exporter-1  |            ^^^^^^^^^^^^^^^^^^^
rundeck-rundeck_exporter-1  |   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
rundeck-rundeck_exporter-1  |     return self.__get_result()
rundeck-rundeck_exporter-1  |   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
rundeck-rundeck_exporter-1  |     raise self._exception
rundeck-rundeck_exporter-1  |   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
rundeck-rundeck_exporter-1  |     result = self.fn(*self.args, **self.kwargs)
rundeck-rundeck_exporter-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rundeck-rundeck_exporter-1  |   File "/app/rundeck_exporter.py", line 309, in get_project_executions
rundeck-rundeck_exporter-1  |     return project_execution_records, project_executions_total
rundeck-rundeck_exporter-1  |                                       ^^^^^^^^^^^^^^^^^^^^^^^^
rundeck-rundeck_exporter-1  | UnboundLocalError: cannot access local variable 'project_executions_total' where it is not associated with a value
```

This doesn’t prevent the exporter to run but we would like to share this situation.

Thanks

**Comment by phsmith** [comment]
Thanks for the report @Zwordi.
I've identified the problem and it will be fixed in the next release.

**Comment by Zwordi** [comment]
Hi,
Great to know :)
Thanks,

**Comment by phsmith** [comment]
Hi @Zwordi, 

The rundeck_exporter [v2.7.0](https://github.com/phsmith/rundeck_exporter/releases/tag/v2.7.0) has been released and might fix this problem.
If you get a chance, please try the new version and let me know.

**Comment by Zwordi** [comment]
Hi,

Will be done this week. I will let you know.

Thanks,

20 avr. 2024 16:25:26 Phillipe Smith ***@***.***>:

**Comment by Zwordi** [comment]
I just deployed your latest version in few VMs no more output about this issue visible. 
Closing this issue. 
Thanks,
